
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1120x640")
window.configure(bg = "#8FA293")


canvas = Canvas(
    window,
    bg = "#8FA293",
    height = 640,
    width = 1120,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    49.032257080078125,
    25.80645751953125,
    1056.7742004394531,
    99.35484313964844,
    fill="#C4E9E9",
    outline="")

canvas.create_rectangle(
    49.0,
    132.0,
    810.0,
    480.0,
    fill="#C5EAEA",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    428.5,
    302.0,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#FBF7F7",
    highlightthickness=0
)
entry_1.place(
    x=70.0,
    y=165.0,
    width=717.0,
    height=272.0
)

canvas.create_text(
    133.0,
    162.0,
    anchor="nw",
    text="Pregunta 1\n\n¿Cuál fue...?",
    fill="#000000",
    font=("Roboto Black", 30 * -1)
)

canvas.create_text(
    140.96774291992188,
    50.6129150390625,
    anchor="nw",
    text="Te doy la bienvenida al juego de Preguntas y Respuestas, ¡¡espero te diviertas!!",
    fill="#000000",
    font=("Roboto Black", 23 * -1)
)

canvas.create_rectangle(
    838.7096557617188,
    129.03225708007812,
    1058.0644989013672,
    619.3548278808594,
    fill="#C5EAEA",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=77.0,
    y=502.0,
    width=341.0,
    height=52.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=452.0,
    y=502.0,
    width=333.0,
    height=52.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=77.0,
    y=570.0,
    width=341.0,
    height=53.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=452.0,
    y=570.0,
    width=333.0,
    height=53.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=845.0,
    y=559.0,
    width=205.0,
    height=47.0
)

canvas.create_text(
    870.9677124023438,
    136.77420043945312,
    anchor="nw",
    text="Premios",
    fill="#000000",
    font=("Roboto Black", 30 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    948.0,
    325.0,
    image=entry_image_2
)
entry_2 = Text(
    bd=0,
    bg="#FBEEEE",
    highlightthickness=0
)
entry_2.place(
    x=850.0,
    y=170.0,
    width=196.0,
    height=308.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    948.0,
    523.5,
    image=entry_image_3
)
entry_3 = Text(
    bd=0,
    bg="#FBEEEE",
    highlightthickness=0
)
entry_3.place(
    x=850.0,
    y=507.0,
    width=196.0,
    height=31.0
)
window.resizable(False, False)
window.mainloop()
